-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 00:12:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/*SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;*/
/*SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;*/
/*SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';*/

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `surname` VARCHAR(128) NULL DEFAULT NULL,
  `email` VARCHAR(128) NULL DEFAULT NULL,
  `role` VARCHAR(128) NULL DEFAULT NULL,
  `password_hash` CHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account` (
  `id` INT NOT NULL,
  `number` VARCHAR(128) NULL DEFAULT NULL,
  `balance` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `card` (
  `id` INT NOT NULL,
  `accountID` INT NULL,
  `number` VARCHAR(16) NULL,
  `date` VARCHAR(5) NULL,
  `name` VARCHAR(64) NULL,
  `blocked` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  KEY `accountID` (`accountID`),
  CONSTRAINT `accountID` FOREIGN KEY (`accountID`) REFERENCES `account` (`id`))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `association` (
  `id` INT NOT NULL,
  `userID` INT NULL,
  `cardID` INT NULL,
  PRIMARY KEY (`id`),
  KEY `userID` (`userID`),
  KEY `cardID` (`cardID`),
  CONSTRAINT `userID` FOREIGN KEY (`userID`) REFERENCES `bank`.`user` (`id`),
  CONSTRAINT `cardID` FOREIGN KEY (`cardID`) REFERENCES `bank`.`card` (`id`))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
